export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST';
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_GET_OTP_REQUEST_SUCCESS = 'USER_GET_OTP_REQUEST_SUCCESS';
export const USER_GET_OTP_REQUEST_FAIL = 'USER_GET_OTP_REQUEST_FAIL';
export const USER_SIGNUP_SIGNIN_ERROR = 'USER_SIGNUP_SIGNIN_ERROR';
export const CHANGE_USER_AVATAR_MODAL = 'CHANGE_USER_AVATAR_MODAL';
export const USER_WALLET_AND_GAME_BALANCE_REQUEST = 'USER_WALLET_AND_GAME_BALANCE_REQUEST';
export const USER_WALLET_AND_GAME_BALANCE_SUCCESS = 'USER_WALLET_AND_GAME_BALANCE_SUCCESS';

export const USER_BET_PREDICTION_HISTORY_REQUEST = 'USER_BET_PREDICTION_HISTORY_REQUEST';
export const USER_BET_PREDICTION_HISTORY_SUCCESS = 'USER_BET_PREDICTION_HISTORY_SUCCESS';

export const USER_BET_PREDICTION_STATUS_LOADING_REQUEST = 'USER_BET_PREDICTION_STATUS_LOADING_REQUEST';
export const USER_BET_PREDICTION_STATUS_EXPIRED = 'USER_BET_PREDICTION_STATUS_EXPIRED';
export const USER_BET_PREDICTION_STATUS_WAITING = 'USER_BET_PREDICTION_STATUS_WAITING';
export const USER_BET_PREDICTION_STATUS_READY = 'USER_BET_PREDICTION_STATUS_READY';
export const USER_BET_PREDICTION_STATUS = 'USER_BET_PREDICTION_STATUS';
export const USER_BET_PREDICTION_STATUS_READY_TIMER = 'USER_BET_PREDICTION_STATUS_READY_TIMER';
export const USER_BET_PREDICTION_STATUS_TIMER = 'USER_BET_PREDICTION_STATUS_TIMER';
